function [Sx, Sy] = computeInconsistency(Gx_q, Gx_m, Gy_q, Gy_m)
[Vx, Vy] = generateFalseMap(Gx_q, Gx_m, Gy_q, Gy_m);
[Sx, Sy] = sumFalseMap(Vx, Vy);
end

function [Vx, Vy] = generateFalseMap(Gx_q, Gx_m, Gy_q, Gy_m)
% XOR operation of Gx and Gy in according axis. Reference:formula (6) and
% (7) in "Spatial Coding for Large Scale Partial-Duplicate Web Image
% Search" (wengang zhou)
% Gx_q is geometric map of query in x axis, Gx_m is geometric map of
% database image in x axis, Gy_q is geometric map of query in y axis, Gy_m
% is geometric map of database in y axis.
Vx = xor(Gx_q, Gx_m);
Vy = xor(Gy_q, Gy_m);
end

function [Sx, Sy] = sumFalseMap(Vx, Vy)
% Reference: formula (8) in "Spatial Coding for Large Scale Partial-Duplicate Web Image
% Search" (wengang zhou)
% Vx and Vy are false map generated by XOR operation between query and
% database images.
Sx = sum(sum(Vx, 3), 2);
Sy = sum(sum(Vy, 3), 2);
end